### ISSUE TITLE
YouTube stream fails with could not extract stream for this track

### ISSUE THREAD

**Issue by skdhg** [Androz2091/discord-player#1705]
Discord Player throws `could not extract stream for this track` when trying to stream youtube source. This affects all the extractors that depend upon youtube streaming:

* spotify extractor
* apple music extractor
* youtube extractor

**Update 1**
Streaming works upon removing `ytdl-core` and installing `play-dl`. This seems to be [node-ytdl-core](https://github.com/fent/node-ytdl-core) issue as mentioned in https://github.com/fent/node-ytdl-core/issues/1197. As a workaround, follow these steps:
1. `npm install play-dl` or `npm install @distube/ytdl-core`
2. add `DP_FORCE_YTDL_MOD="play-dl"` or `DP_FORCE_YTDL_MOD="@distube/ytdl-core"` in your `.env` file

If `npm` doesn't work, clear npm cache and try again, or switch to another package manager like `yarn`.

**Comment by NerdyTechy** [comment]
@discord-player/extractor has ytdl-core as a peer dependency, so if you're using that you'll want to install play-dl then delete the ytdl-core folder inside of node_modules

**Comment by skdhg** [comment]
> @discord-player/extractor has ytdl-core as a peer dependency, so if you're using that you'll want to install play-dl then delete the ytdl-core folder inside of node_modules

You don't have to modify `node_modules`. Set `DP_FORCE_YTDL_MOD="play-dl"` environment variable.

**Comment by Mittelblut9** [comment]
I have followed the workaround, but it's still failing 
![grafik](https://user-images.githubusercontent.com/67608550/230160862-8270a74b-a008-4a95-9dde-78cf6bbde33b.png)

Song Link: https://open.spotify.com/track/1SOTqkhpIWoLX1AS9Y2RpU

**Comment by DroppedCoin375** [comment]
Downgrading to ytdl-core@4.9.1 worked for me

**Comment by skdhg** [comment]
> I have followed the workaround, but it's still failing ![grafik](https://user-images.githubusercontent.com/67608550/230160862-8270a74b-a008-4a95-9dde-78cf6bbde33b.png)
> 
> Song Link: https://open.spotify.com/track/1SOTqkhpIWoLX1AS9Y2RpU

Try clearing npm cache or use another package manager like yarn.

**Comment by Donoso005** [comment]
Downgrade the ytdl-core package to ytdl-core@4.9.1, like that:
    "ytdl-core": "4.9.1"

**Comment by fpsone** [comment]
Downgrading to `ytdl-core@4.9.1` make the stream url download bottleneck and the music is not playing smoothly
`play-dl` can play normal youtube link but it doesn't support live stream url (`Error: Could not extract stream for this track`)
 
**My solution**
Using `@distube/ytdl-core` fork (https://github.com/Androz2091/discord-player#streaming-library)

1. `npm i @distube/ytdl-core@latest`
2. Set `DP_FORCE_YTDL_MOD="@distube/ytdl-core"` environment variable

This should make your bot play youtube stream smoothly and play live stream normally

**Comment by Donoso005** [comment]
How can i setup the enviroment variable, where is the variable?

**Comment by skdhg** [comment]
> How can i setup the enviroment variable, where is the variable?

You can set it in your `.env` file or via cli

**Comment by khlevon** [comment]
For fix check this comment: https://github.com/fent/node-ytdl-core/issues/1197#issuecomment-1499346540

**Comment by Donoso005** [comment]
> > How can i setup the enviroment variable, where is the variable?
> 
> You can set it in your `.env` file or via cli

And then What am I supposed to do with that variable?

**Comment by Donoso005** [comment]
> > How can i setup the enviroment variable, where is the variable?
> 
> You can set it in your `.env` file or via cli

And then What am I supposed to do with that variable?

**Comment by skdhg** [comment]
> And then What am I supposed to do with that variable?
You don't have to do anything with the environment variable in your code. The `DP_` prefixed environment variables change the behavior of `discord-player`. In this case, `DP_FORCE_YTDL_MOD` variable makes `discord-player` prioritize the given ytdl module.

**Comment by bagelwastaken** [comment]
> Downgrading to ytdl-core@4.9.1 worked for me

Yup, worked for me as well.

**Comment by rayan1812109** [comment]
"Just discovered MusConv and it's a game-changer for managing my music collection! Highly recommend checking it out: http://www.musconv.com/ #musicmanagement #musictool #musconv"

**Comment by skdhg** [comment]
The issue has been fixed https://github.com/fent/node-ytdl-core/releases/tag/v4.11.4

**Comment by skdhg** [comment]
https://github.com/fent/node-ytdl-core/issues/1216

**Comment by zachrussell12** [comment]
This is still an issue as of ytdl-core@4.11.4. Downgrading to 4.9.1 fixed the issue for now.

**Comment by skdhg** [comment]
We support the following youtube streaming libs:

- [`ytdl-core`](https://npm.im/ytdl-core)
- [`@distube/ytdl-core`](https://npm.im/@distube/ytdl-core)
- [`play-dl`](https://npm.im/play-dl)
- [`yt-stream`](https://npm.im/yt-stream)

If `ytdl-core` is not working, try another lib (`process.env.DP_FORCE_YTDL_MOD` supports all of these libs).
